// <auto-generated />
using System;
using Employeeprj.Models;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace Employeeprj.Migrations
{
    [DbContext(typeof(MYPRJContext))]
    [Migration("20210719172457_abc")]
    partial class abc
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("ProductVersion", "5.0.7")
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("Employeeprj.Models.NATIONALITY", b =>
                {
                    b.Property<int>("NATId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("DESC")
                        .HasColumnType("nvarchar(max)");

                    b.Property<double?>("NAT_CODE")
                        .HasColumnType("float");

                    b.HasKey("NATId");

                    b.ToTable("NATIONALITY");
                });

            modelBuilder.Entity("Employeeprj.Models.PYALW", b =>
                {
                    b.Property<int>("ALWId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int?>("ALW_CODE")
                        .HasColumnType("int");

                    b.Property<string>("ALW_TYPE")
                        .HasColumnType("nvarchar(max)");

                    b.Property<decimal?>("AMOUNT")
                        .HasColumnType("decimal(18,2)");

                    b.Property<double?>("EMP_NO")
                        .HasColumnType("float");

                    b.Property<int?>("STOP_ID")
                        .HasColumnType("int");

                    b.HasKey("ALWId");

                    b.ToTable("PYALWs");
                });

            modelBuilder.Entity("Employeeprj.Models.PYDEPT", b =>
                {
                    b.Property<int>("DEPId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<double?>("DEP_CODE")
                        .HasColumnType("float");

                    b.Property<string>("DESC")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("SECId")
                        .HasColumnType("int");

                    b.Property<int?>("SECTIONSECId")
                        .HasColumnType("int");

                    b.HasKey("DEPId");

                    b.HasIndex("SECTIONSECId");

                    b.ToTable("PYDEPT");
                });

            modelBuilder.Entity("Employeeprj.Models.PYEmployee", b =>
                {
                    b.Property<int>("EMPId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int>("ALWId")
                        .HasColumnType("int");

                    b.Property<int>("DEPId")
                        .HasColumnType("int");

                    b.Property<DateTime>("DT_OF_BRTH")
                        .HasColumnType("datetime2");

                    b.Property<double?>("EMP_NO")
                        .HasColumnType("float");

                    b.Property<string>("MARITAL_ST")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("NAME")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("NATIONALITYsNATId")
                        .HasColumnType("int");

                    b.Property<int>("NATId")
                        .HasColumnType("int");

                    b.Property<int?>("PYALWsALWId")
                        .HasColumnType("int");

                    b.Property<int?>("PYDEPTsDEPId")
                        .HasColumnType("int");

                    b.Property<int?>("PYSCMSCMId")
                        .HasColumnType("int");

                    b.Property<int>("RANKId")
                        .HasColumnType("int");

                    b.Property<string>("REASON")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("SALARY_CHANGESALCHANGEId")
                        .HasColumnType("int");

                    b.Property<int>("SALCHANGEId")
                        .HasColumnType("int");

                    b.Property<int>("SCHId")
                        .HasColumnType("int");

                    b.Property<int?>("SCH_CODEsSCHId")
                        .HasColumnType("int");

                    b.Property<int>("SCMId")
                        .HasColumnType("int");

                    b.Property<int>("SECId")
                        .HasColumnType("int");

                    b.Property<int?>("SECTIONsSECId")
                        .HasColumnType("int");

                    b.Property<string>("SEX")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("STOP_ID")
                        .HasColumnType("int");

                    b.HasKey("EMPId");

                    b.HasIndex("NATIONALITYsNATId");

                    b.HasIndex("PYALWsALWId");

                    b.HasIndex("PYDEPTsDEPId");

                    b.HasIndex("PYSCMSCMId");

                    b.HasIndex("RANKId");

                    b.HasIndex("SALARY_CHANGESALCHANGEId");

                    b.HasIndex("SCH_CODEsSCHId");

                    b.HasIndex("SECTIONsSECId");

                    b.ToTable("PYEmployee");
                });

            modelBuilder.Entity("Employeeprj.Models.PYSCM", b =>
                {
                    b.Property<int>("SCMId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("DESC")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("SCHId")
                        .HasColumnType("int");

                    b.Property<int?>("SCH_CODESCHId")
                        .HasColumnType("int");

                    b.Property<double?>("SCM_CODE")
                        .HasColumnType("float");

                    b.HasKey("SCMId");

                    b.HasIndex("SCH_CODESCHId");

                    b.ToTable("PYSCM");
                });

            modelBuilder.Entity("Employeeprj.Models.Rank", b =>
                {
                    b.Property<int>("RANKId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<double?>("RNK_CODE")
                        .HasColumnType("float");

                    b.Property<string>("RNK_DESC")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("RANKId");

                    b.ToTable("Rank");
                });

            modelBuilder.Entity("Employeeprj.Models.SALARY_CHANGE", b =>
                {
                    b.Property<int>("SALCHANGEId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<double?>("EMP_NO")
                        .HasColumnType("float");

                    b.Property<double?>("NEW_BASIC")
                        .HasColumnType("float");

                    b.Property<double?>("OLD_BASIC")
                        .HasColumnType("float");

                    b.Property<DateTime>("TRN_DATE")
                        .HasColumnType("datetime2");

                    b.Property<string>("TRN_DESC")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("TRN_PERIOD")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("SALCHANGEId");

                    b.ToTable("SALARY_CHANGE");
                });

            modelBuilder.Entity("Employeeprj.Models.SCH_CODE", b =>
                {
                    b.Property<int>("SCHId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("BASIC")
                        .HasColumnType("nvarchar(max)");

                    b.Property<double>("SECH_CODE")
                        .HasColumnType("float");

                    b.Property<string>("STEP_CODE")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("SCHId");

                    b.ToTable("SCH_CODE");
                });

            modelBuilder.Entity("Employeeprj.Models.SECTION", b =>
                {
                    b.Property<int>("SECId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("DESC")
                        .HasColumnType("nvarchar(max)");

                    b.Property<double?>("SEC_CODE")
                        .HasColumnType("float");

                    b.HasKey("SECId");

                    b.ToTable("SECTION");
                });

            modelBuilder.Entity("Employeeprj.Models.PYDEPT", b =>
                {
                    b.HasOne("Employeeprj.Models.SECTION", "SECTION")
                        .WithMany()
                        .HasForeignKey("SECTIONSECId");

                    b.Navigation("SECTION");
                });

            modelBuilder.Entity("Employeeprj.Models.PYEmployee", b =>
                {
                    b.HasOne("Employeeprj.Models.NATIONALITY", "NATIONALITYs")
                        .WithMany()
                        .HasForeignKey("NATIONALITYsNATId");

                    b.HasOne("Employeeprj.Models.PYALW", "PYALWs")
                        .WithMany()
                        .HasForeignKey("PYALWsALWId");

                    b.HasOne("Employeeprj.Models.PYDEPT", "PYDEPTs")
                        .WithMany()
                        .HasForeignKey("PYDEPTsDEPId");

                    b.HasOne("Employeeprj.Models.PYSCM", "PYSCM")
                        .WithMany()
                        .HasForeignKey("PYSCMSCMId");

                    b.HasOne("Employeeprj.Models.Rank", "Rank")
                        .WithMany()
                        .HasForeignKey("RANKId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Employeeprj.Models.SALARY_CHANGE", "SALARY_CHANGE")
                        .WithMany()
                        .HasForeignKey("SALARY_CHANGESALCHANGEId");

                    b.HasOne("Employeeprj.Models.SCH_CODE", "SCH_CODEs")
                        .WithMany()
                        .HasForeignKey("SCH_CODEsSCHId");

                    b.HasOne("Employeeprj.Models.SECTION", "SECTIONs")
                        .WithMany()
                        .HasForeignKey("SECTIONsSECId");

                    b.Navigation("NATIONALITYs");

                    b.Navigation("PYALWs");

                    b.Navigation("PYDEPTs");

                    b.Navigation("PYSCM");

                    b.Navigation("Rank");

                    b.Navigation("SALARY_CHANGE");

                    b.Navigation("SCH_CODEs");

                    b.Navigation("SECTIONs");
                });

            modelBuilder.Entity("Employeeprj.Models.PYSCM", b =>
                {
                    b.HasOne("Employeeprj.Models.SCH_CODE", "SCH_CODE")
                        .WithMany()
                        .HasForeignKey("SCH_CODESCHId");

                    b.Navigation("SCH_CODE");
                });
#pragma warning restore 612, 618
        }
    }
}
